name: conda_skills
channels:
- https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
- https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
- defaults
- https://repo.anaconda.com/pkgs/main
- https://repo.anaconda.com/pkgs/r
- https://repo.anaconda.com/pkgs/msys2
dependencies:
- bzip2=1.0.8
- ca-certificates=2025.12.2
- expat=2.7.4
- libexpat=2.7.4
- libffi=3.4.4
- libzlib=1.3.1
- openssl=3.0.19
- packaging=25.0
- pip=25.3
- python=3.10.19
- setuptools=80.10.2
- sqlite=3.51.1
- tk=8.6.15
- tzdata=2025c
- ucrt=10.0.22621.0
- vc=14.3
- vc14_runtime=14.44.35208
- vs2015_runtime=14.44.35208
- wheel=0.46.3
- xz=5.6.4
- zlib=1.3.1
- pip:
  - annotated-doc==0.0.4
  - annotated-types==0.7.0
  - anyio==4.12.1
  - certifi==2026.1.4
  - charset-normalizer==3.4.4
  - click==8.3.1
  - colorama==0.4.6
  - exceptiongroup==1.3.1
  - fastapi==0.128.4
  - h11==0.16.0
  - httptools==0.7.1
  - idna==3.11
  - pydantic==2.12.5
  - pydantic-core==2.41.5
  - python-dotenv==1.2.1
  - pyyaml==6.0.3
  - requests==2.32.5
  - starlette==0.52.1
  - typing-extensions==4.15.0
  - typing-inspection==0.4.2
  - urllib3==2.6.3
  - uvicorn==0.40.0
  - watchfiles==1.1.1
  - websockets==16.0
